# Solopreneur Community Project Configuration
# 솔로프러너/1인창업을 위한 정보 공유 커뮤니티

project:
  id: solopreneur-community
  name: Solopreneur Community
  description: 솔로프러너/1인창업자를 위한 수익화 정보 공유 커뮤니티 - 새 시장 감지, 수익 사례, 기술 스택 정보
  owner: org-tinysolver
  status: active  # active | paused | completed | archived

# 담당 팀
assigned_team: devteam

# 구현체 위치
implementation:
  target: org-tinysolver/ai-devteam/apps/solopreneur-community

# 왜 이 프로젝트를 하는가?
motivation:
  problem: |
    솔로프러너/1인창업자가 새로운 시장 기회를 빠르게 캐치하고,
    실제로 돈을 버는 검증된 사례를 찾기 어려움.
    양질의 정보와 저질 정보를 구분하기 힘듦.
  why_now: |
    AI 도구 시장(Claude 플러그인, GPT Store 등) 급성장 중.
    1인 창업 트렌드 가속화. 지금 시작해야 선점 가능.
  expected_outcome: |
    - 새 시장/플랫폼 오픈 정보 빠른 공유
    - 실제 수익 사례 아카이브 (인증 시스템)
    - 1인 운영 가능한 기술 스택 정보 공유
    - 프리미엄 멤버십으로 수익화
  personal_value: |
    커뮤니티 플랫폼 개발 경험. SaaS 멤버십 모델 검증.

# 비슷한 기존 프로젝트 확인
related_check:
  checked_at: 2025-01-15
  similar_projects: []
  decision: "새로 시작 - 기존에 유사 프로젝트 없음"

repository:
  url: https://github.com/org-tinysolver/ai-devteam
  default_branch: main
  path_in_repo: apps/solopreneur-community

# GitHub Projects Board (프로젝트 보드)
board:
  name: "[PRODUCT] Solopreneur Community"
  number: 7
  url: https://github.com/orgs/org-tinysolver/projects/7

# 핵심 요구사항 (WHAT - 무엇이 필요한가)
requirements:
  # 핵심 기능 요구사항
  features:
    - name: auth
      description: 회원가입/로그인 (소셜 로그인 포함)
    - name: problem-board
      description: AI 서비스 관련 문제 등록/조회 (수요자)
    - name: solver-matching
      description: 해결자 등록 및 문제-해결자 매칭
    - name: chat
      description: 1:1 실시간 채팅 (문제 해결 소통)
    - name: premium-membership
      description: 유료 멤버십 결제 및 구독 관리
    - name: protocol-data
      description: 소통 프로토콜 데이터 축적 (핵심 경쟁력)

  # 비기능 요구사항
  non_functional:
    - 빠른 MVP 런칭 (lean startup)
    - 1인 운영 가능한 관리 복잡도
    - 실시간 채팅 지원
    - 결제 시스템 안정성

# HITL 체크포인트 (인간 승인 필요)
hitl_checkpoints:
  required:
    - before_deploy_production
    - payment_integration
    - domain_setup
    - oauth_provider_setup
  optional:
    - design_review

# 기술 스택 - DevTeam이 결정
# (PM은 요구사항만 정의, 기술 선택은 DevTeam 자율)

keywords:
  - solopreneur
  - community
  - startup
  - indie-hacker
  - monetization
  - ai-tools
  - side-hustle
  - matching
  - consulting

notifications:
  on_deploy: true
  on_error: true
  on_hitl_required: true
